# Generated by Django 5.0.4 on 2024-04-19 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='id')),
                ('original_title', models.CharField(max_length=255, verbose_name='titre original')),
                ('romanized_title', models.CharField(max_length=255, verbose_name='titre romanisé')),
                ('french_title', models.CharField(max_length=255, verbose_name="pays d'origine")),
                ('country', models.CharField(max_length=255, verbose_name='titre français')),
                ('release_date', models.DateField(verbose_name='date de sortie')),
                ('language', models.CharField(max_length=20, verbose_name='langue')),
                ('time_length', models.IntegerField(verbose_name='durée')),
                ('genres', models.CharField(max_length=255, verbose_name='genres')),
                ('keywords', models.IntegerField(verbose_name='keywords')),
                ('budget', models.BigIntegerField(default=0, verbose_name='budget')),
                ('revenue', models.BigIntegerField(default=0, verbose_name='revenue')),
                ('prod_comp', models.TextField(default='inconnu', verbose_name='société de production')),
                ('prod_countries', models.CharField(default='inconnu', max_length=255, verbose_name='pays de production')),
                ('avg_rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='note Moyenne')),
                ('count_rating', models.BigIntegerField(verbose_name='nombre Vote')),
                ('directors', models.CharField(default='inconnu', max_length=255, verbose_name='réalisateurs')),
                ('writers', models.CharField(default='inconnu', max_length=255, verbose_name='scénaristes')),
                ('poster', models.CharField(max_length=255, verbose_name='poster_path')),
                ('theme', models.CharField(max_length=20, verbose_name='thème')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('gender', models.CharField(max_length=1, verbose_name='genre')),
                ('character', models.CharField(default='inconnu', max_length=100, verbose_name='personnage')),
                ('movie_id', models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='home.film', verbose_name='id_film')),
            ],
        ),
    ]
